// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB90gXXiPmA-rkIn3gttJuCCO2SF3omq4g',
    appId: '1:1062882462307:android:ae9d7a81a6339785fec656',
    messagingSenderId: '1062882462307',
    projectId: 'developer-db09e',
    storageBucket: 'developer-db09e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDn8IVmRvDQW5sIKrsq0aI5Om5ha-_w_QA',
    appId: '1:1062882462307:ios:c201ba6a2ebbcd4bfec656',
    messagingSenderId: '1062882462307',
    projectId: 'developer-db09e',
    storageBucket: 'developer-db09e.firebasestorage.app',
    iosClientId: '1062882462307-5f9o7hk53lu2c3pn52juf1d25aaco5j5.apps.googleusercontent.com',
    iosBundleId: 'com.example.developer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDK66FQbLffvQISBtibHQbFkZUJHB7Mafk',
    appId: '1:1062882462307:web:1e356ea049815422fec656',
    messagingSenderId: '1062882462307',
    projectId: 'developer-db09e',
    authDomain: 'developer-db09e.firebaseapp.com',
    storageBucket: 'developer-db09e.firebasestorage.app',
    measurementId: 'G-CVK9KRMD2Y',
  );
}
